# Monitoring Report — {{ observed_at }}

Time range: {{ time_range.start }} to {{ time_range.end }} ({{ time_range.label }})

Project count: {{ project_count }}

{{#projects}}
## {{ project }}

### Datadog

**Status: {{ datadog.status | upper }}**

{{ datadog.summary }}

{{#datadog.monitors_table}}
| Monitor | State | Threshold |
|---------|-------|-----------|
{{#monitors}}
| {{ name }} | {{ state }} | {{ threshold }} |
{{/monitors}}
{{/datadog.monitors_table}}

### Stability SDK

**Status: {{ stability_sdk.status | upper }}**{{ #stability_sdk.provisional }} (provisional data){{ /stability_sdk.provisional }}

{{ stability_sdk.summary }}

| Metric | Current | Baseline | Change |
|--------|---------|----------|--------|
| Total errors | {{ stability_sdk.curr_total }} | {{ stability_sdk.base_total }} | {{ stability_sdk.change_pct }}% |
| Error rate (per {{ stability_sdk.rate_unit }}) | {{ stability_sdk.curr_rate }} | {{ stability_sdk.base_rate }} | {{ stability_sdk.change_pct }}% |
| P0 categories | {{ stability_sdk.p0_count }} | — | — |
| Spike alerts | {{ stability_sdk.spike_count }} | — | — |

**Top P0 issues:**
{{#stability_sdk.top_issues}}
{{ idx }}. {{ description }}
{{/stability_sdk.top_issues}}

### Sentry

**Status: {{ sentry.status | upper }}**

{{ sentry.summary }}

| Window | Errors |
|--------|--------|
| Current ({{ sentry.current_window }}) | {{ sentry.current }} |
| Baseline ({{ sentry.baseline_window }}) | {{ sentry.baseline }} |
| **Delta** | **{{ sentry.delta }} ({{ sentry.delta_percent }}%)** |

### tracking_patrol

**Status: {{ tracking_patrol.status | upper }}**

{{ tracking_patrol.summary }}

{{/projects}}

---

## Evidence

| Signal | Path |
|--------|------|
{{#evidence_files}}
| {{ signal }} | `{{ path }}` |
{{/evidence_files}}

---

*Run ID: `{{ run_id }}` · Generated by monitoring-orchestrator*
